### ISSUE TITLE
parent_id = null

### ISSUE THREAD

**Issue by zertex** [paulzi/yii2-adjacency-list#7]
Здравствуйте!

При создании ROOT ноды в параметре parent_id прописывается в MySQL как NULL
В этом случае нет возможности перенести другую ноду по отношению к этой по before/after

А вот если эту ноду (с параметром parent_id = NULL) перенести дочерней к какой-нибудь другой ноде и затем перетянуть обратно, то parent_id у нее уже 0 и все работает корректно...

Можно ли как-то при создании ROOT ноды сделать parent_id = 0?

P.S. Хотя и с нулевым parent_id insertBefore/After не всегда переносят ноду... Непонятно

**Comment by paulzi** [comment]
Рутовые ноды нельзя сортировать между собой by design.  Это было сделано для совместимости с различными методами хранения, в частности с Nested Sets. Т. к. в NS узлы сортируются по lft, который для корневого узла всегда равен 1.
Обычно, необходимость сортировки корневых узлов решается путём переноса всех узлов в первый уровень под один общий корневой узел.
По поводу того, что parent_id становится 0, так быть не должно, проверю.

**Comment by paulzi** [comment]
Через тесты не удалось воспроизвести ситуацию. Проверяйте ваши схемы, возможно там стоит default значение ноль.
https://github.com/paulzi/yii2-adjacency-list/commit/da79542fd1070c2227780b1e606ed7ec4387db69
